stages:
  - build
  - deploy

build-react-app:
  stage: build
  image: node:16-alpine
  script:
    - npm ci
    - npm run build
  artifacts:
    paths:
      - ./build

deploy-react-app:
  stage: deploy
  image:
    name: amazon/aws-cli
    entrypoint: [""]
  when: manual
  script:
    - aws s3 sync ./build/ s3://react-app-static-website-bucket